#!/bin/bash


## CPU
cpu() {
  read cpu a b c previdle rest < /proc/stat
  prevtotal=$((a+b+c+previdle))
  sleep 0.5
  read cpu a b c idle rest < /proc/stat
  total=$((a+b+c+idle))
  cpu=$((100*( (total-prevtotal) - (idle-previdle) ) / (total-prevtotal) ))
  echo -e "$cpu%"
}

## RAM
mem() {
  mem="$(free -h | awk '/^Mem/ { print $3 }' | sed s/i//g)"
  echo -e "$mem"
}

## DISK
hdd() {
  hdd="$(df -h | awk 'NR==4{print $3, $5}')"
  echo -e "$hdd"
}

## TEMP
temp() {
#TEMP="$(sensors|awk 'BEGIN{i=0;t=0;b=0}/id [0-9]/{b=$4};/Core/{++i;t+=$3}END{if(i>0){printf("%0.1f\n",t/i)}else{sub(/[^0-9.]/,"",b);print b}}')"
TEMP="$(sensors|awk '/Tctl/{print substr($2,2,2)}')°C"
echo -e  "$TEMP"
}

## GPU
gpu() {
  GPU="$(nvidia-smi|awk 'NR==10{print substr($3,1,2)}')°C"
  echo -e "$GPU"
}


## BATT
power() {
PWR=$(cat /sys/class/power_supply/BAT0/capacity)
echo -e "$PWR%"
}

## VOL
volume() {
VOL="$(awk -F"[][]" '/Left:/ { print $2 }' <(amixer sget Master))"
echo -e "$VOL"
}

## SCREEN BRIGHTNESS
backlight() {
BLT="$(xbacklight -get | awk '{print int($1)}')"
echo -e "$BLT%"	
}

while true; do
  cupd=$(checkupdates | wc -l | head -c3 )
  echo -e "$cupd" > /home/sanjay/Applications/dwmscripts/dwmupdates.txt
  weather="$(python ~/Applications/dwmscripts/weather.py)"
  echo -e "$weather" > /home/sanjay/Applications/dwmscripts/weather.txt
	sleep 1800s
done &

## UPDATES
upd() {
PAC=$(< /home/sanjay/Applications/dwmscripts/dwmupdates.txt)
echo -e "$PAC"
}

## Weather
weather() {
WEA=$(< /home/sanjay/Applications/dwmscripts/weather.txt)
echo -e "$WEA"
}

## DATE
clock() {
dte="$(date +"%a, %b %d %l:%M%p"| sed 's/  / /g')"
echo -e "$dte"
}


## NET
net() {
  speed="$(python ~/Applications/dwmscripts/net.py)"
  echo -e "$speed"
}


while true; do

#xsetroot -name "|  $(cpu) |  $(mem) |   $(hdd) |  $(power) |  $(temp) |   $(volume) | $(date) |"
#xsetroot -name "| ^c#d08770^$(cpu)^d^ | ^c#5e81ac^$(mem)^d^ | ^c#bf616a^$(temp)^d^ | ^c#a3be8c^$(gpu)^d^ | ^c#d08770^$(net)^d^ | ^c#8fbcbb^$(volume)^d^ | ^c#81a1c1^$(upd)^d^ |^c#93a1a1^$(clock)^d^"
xsetroot -name "^c#d08770^$(cpu)^d^ ^c#5e81ac^$(mem)^d^ ^c#bf616a^$(temp)^d^ ^c#a3be8c^$(gpu)^d^ ^c#d08770^$(net)^d^ ^c#8fbcbb^$(volume)^d^ ^c#81a1c1^$(upd)^d^ ^c#d08770^$(weather)^d^ ^c#93a1a1^$(clock)^d^"
#  |^c#b48ead^  $(power)^d^ 	|^c#ebcb8b^   $(backlight)^d^   
	sleep 5s
	
done &

